CREATE TABLE user_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL
);

ALTER TABLE user_items ADD CONSTRAINT pk_user_items PRIMARY KEY (id);
ALTER TABLE user_items ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES usuario(id);
ALTER TABLE user_items ADD CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES item(id);
