CREATE TABLE permission (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	user_id BIGINT NOT NULL
);

ALTER TABLE permission ADD CONSTRAINT pk_permission PRIMARY KEY (id);
ALTER TABLE permission ADD CONSTRAINT uk_permission UNIQUE (name, user_id);
ALTER TABLE permission ADD CONSTRAINT fk_permission_user FOREIGN KEY (user_id) REFERENCES usuario(id);


INSERT INTO public."permission"
(id, "name", user_id)
VALUES(1000000000, 'ADMIN', 1000000000);

INSERT INTO public."permission"
(id, "name", user_id)
VALUES(1000000001, 'ADMIN', 1000000001);

INSERT INTO public."permission"
(id, "name", user_id)
VALUES(1000000002, 'ADMIN', 1000000002);
