CREATE TABLE user_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    quest_id BIGINT NOT NULL,
    completed_at DATE
);

ALTER TABLE user_quests ADD CONSTRAINT pk_user_quests PRIMARY KEY (id);
ALTER TABLE user_quests ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES usuario(id);
ALTER TABLE user_quests ADD CONSTRAINT fk_quest FOREIGN KEY (quest_id) REFERENCES quest(id);