CREATE TABLE password_reset_token (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   token VARCHAR(255) NOT NULL,
   user_id BIGINT NOT NULL,
   expires_in TIMESTAMP NOT NULL
);

ALTER TABLE password_reset_token ADD CONSTRAINT pk_password_reset_token PRIMARY KEY (id);
ALTER TABLE password_reset_token ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES usuario(id);
