CREATE TABLE item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(512) NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    "price" INTEGER NOT NULL,
    image_url VARCHAR(512) NOT NULL
);

ALTER TABLE item ADD CONSTRAINT pk_item PRIMARY KEY (id);
ALTER TABLE item ADD CONSTRAINT ck_type CHECK(type in ('AVATAR', 'CAPA'));


INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000000, 'avatar01', 'Avatar 01', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar01.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000001, 'avatar02', 'Avatar 02', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar02.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000002, 'avatar03', 'Avatar 03', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar03.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000003, 'avatar04', 'Avatar 04', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar04.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000004, 'avatar05', 'Avatar 05', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar05.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000005, 'avatar06', 'Avatar 06', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar06.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000006, 'avatar07', 'Avatar 07', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar07.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000007, 'avatar08', 'Avatar 08', 'AVATAR', 1000, 'http://localhost:8080/api/static/avatar08.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000008, 'capa01', 'Capa 01', 'CAPA', 1000, 'http://localhost:8080/api/static/banner01.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000009, 'capa02', 'Capa 02', 'CAPA', 1000, 'http://localhost:8080/api/static/banner02.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000010, 'capa03', 'Capa 03', 'CAPA', 1000, 'http://localhost:8080/api/static/banner03.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000011, 'capa04', 'Capa 04', 'CAPA', 1000, 'http://localhost:8080/api/static/banner04.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000012, 'capa05', 'Capa 05', 'CAPA', 1000, 'http://localhost:8080/api/static/banner05.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000013, 'capa06', 'Capa 06', 'CAPA', 1000, 'http://localhost:8080/api/static/banner06.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000014, 'capa07', 'Capa 07', 'CAPA', 1000, 'http://localhost:8080/api/static/banner07.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000015, 'capa08', 'Capa 08', 'CAPA', 1000, 'http://localhost:8080/api/static/banner08.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000016, 'capa09', 'Capa 09', 'CAPA', 1000, 'http://localhost:8080/api/static/banner09.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000017, 'capa10', 'Capa 10', 'CAPA', 1000, 'http://localhost:8080/api/static/banner10.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000018, 'capa11', 'Capa 11', 'CAPA', 1000, 'http://localhost:8080/api/static/banner11.png');

INSERT INTO public.item (id, "name", description, "type", price, image_url)
VALUES(1000000019, 'capa12', 'Capa 12', 'CAPA', 1000, 'http://localhost:8080/api/static/banner12.png');

