CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	username VARCHAR(255),
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	image_profile VARCHAR(512),
	banner_url VARCHAR(512),
	confirm_token CHAR(8) NOT NULL,
	money INTEGER NOT NULL,
	experience BIGINT NOT NULL DEFAULT 0,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ativo BOOLEAN DEFAULT true NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT pk_user PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_user_email UNIQUE (email);


INSERT INTO public.usuario
(id, username, email, "password", image_profile, banner_url, confirm_token, money, experience, created_at, updated_at, ativo)
VALUES(1000000000, 'ismael', 'ismael@cwi.com', '$2a$10$5NDxZtbdWVrBqtgyWuR6teSyIZ78whQ6PEvKu595QZX3UbF.rhFgO', 'http://localhost:8080/api/static/avatar01.png', 'http://localhost:8080/api/static/banner01.png', '03puhr04', 1000000000, 10000, '2023-03-24 11:39:49.641', '2023-03-24 11:39:49.641', true);

INSERT INTO public.usuario
(id, username, email, "password", image_profile, banner_url, confirm_token, money, experience, created_at, updated_at, ativo)
VALUES(1000000001, 'mateus', 'mateus@cwi.com', '$2a$10$FleHljYMc/rtFVMuStTqMuyp8wB2gWq5wJpqYgeadu9.91barktv6', 'http://localhost:8080/api/static/avatar01.png', 'http://localhost:8080/api/static/banner01.png', '0355r806', 1000000000, 10000, '2023-03-24 11:40:08.920', '2023-03-24 11:40:08.920', true);

INSERT INTO public.usuario
(id, username, email, "password", image_profile, banner_url, confirm_token, money, experience, created_at, updated_at, ativo)
VALUES(1000000002, 'jose', 'jose@cwi.com', '$2a$10$rp2xDYBIsMIT1EUGj032veZ6kEIcqHYDn8qXMQoObHCajRC1JJf.W', 'http://localhost:8080/api/static/avatar01.png', 'http://localhost:8080/api/static/banner01.png', '01elmiqr', 1000000000, 10000, '2023-03-24 11:40:20.053', '2023-03-24 11:40:20.053', true);

INSERT INTO public.usuario
(id, username, email, "password", image_profile, banner_url, confirm_token, money, experience, created_at, updated_at, ativo)
VALUES(1000000003, 'lidiane', 'lidiane@cwi.com', '$2a$10$rp2xDYBIsMIT1EUGj032veZ6kEIcqHYDn8qXMQoObHCajRC1JJf.W', 'http://localhost:8080/api/static/avatar01.png', 'http://localhost:8080/api/static/banner01.png', '01elmiqr', 1000000000, 10000, '2023-03-24 11:40:20.053', '2023-03-24 11:40:20.053', true);
