CREATE TABLE friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status varchar(10) NOT NULL DEFAULT 'PENDENTE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES usuario(id),
    FOREIGN KEY (friend_id) REFERENCES usuario(id),
    CHECK (user_id <> friend_id)
);

ALTER TABLE friendship ADD CONSTRAINT pk_amizade PRIMARY KEY (id);
ALTER TABLE friendship ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES usuario(id);
ALTER TABLE friendship ADD CONSTRAINT fk_amigo FOREIGN KEY (friend_id) REFERENCES usuario(id);
ALTER TABLE friendship ADD CONSTRAINT ck_status CHECK(status in ('PENDENTE', 'ACEITA', 'REJEITADA'));