CREATE TABLE chat_room (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      chat_id varchar(255) NOT NULL,
                                      sender_id BIGINT NOT NULL,
                                      receiver_id BIGINT NOT NULL
);

ALTER TABLE chat_room ADD CONSTRAINT pk_chat_room PRIMARY KEY (id);
ALTER TABLE chat_room ADD CONSTRAINT uk_chat_id UNIQUE (chat_id);
ALTER TABLE chat_room ADD CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES usuario(id);
ALTER TABLE chat_room ADD CONSTRAINT fk_receiver FOREIGN KEY (receiver_id) REFERENCES usuario(id);

