CREATE TABLE chat_message (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      chat_id varchar(255) NOT NULL,
                                      receiver_name varchar(255) NOT NULL,
                                      receiver_id BIGINT NOT NULL,
                                      sender_name varchar(255) NOT NULL,
                                      sender_id BIGINT NOT NULL,
                                      msg_content varchar(1024) NOT NULL,
                                      date TIMESTAMP NOT NULL,
                                      status VARCHAR(255) NOT NULL
);

ALTER TABLE chat_message ADD CONSTRAINT pk_chat_msg PRIMARY KEY (id);
ALTER TABLE chat_message ADD CONSTRAINT fk_chat FOREIGN KEY (chat_id) REFERENCES chat_room(chat_id);
ALTER TABLE chat_message ADD CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES usuario(id);
ALTER TABLE chat_message ADD CONSTRAINT fk_receiver FOREIGN KEY (receiver_id) REFERENCES usuario(id);
